version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - BUD_API_KEY=${BUD_API_KEY}
      - BUD_API_SECRET=${BUD_API_SECRET}
      - BUD_BASE_URL=${BUD_BASE_URL}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:8080/dashboard"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s